---
- ansible.builtin.include_tasks: variables.yml

- name: Update apt cache
  apt:
    update_cache: yes
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
  notify: restart mysql
