---
- ansible.builtin.include_tasks: variables.yml

- name: Update apt cache
  apt:
    update_cache: yes
# - name: Install PyMySQL module
#   pip:
#     name: PyMySQL
#     state: latest
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
# - name: Configure MySQL root password
#   mysql_user:
#     name: root
#     password: "{{ mysql_root_password }}"
#     login_unix_socket: /var/run/mysqld/mysqld.sock
#     login_host: localhost
#     login_user: root
#     login_password: ""
#     host_all: yes
#     check_implicit_admin: yes
#     append_privs: yes
#     priv: "*.*:ALL,GRANT"
  notify: restart mysql
